"""
Django settings for MywebTools project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from decouple import config
import os
try:
    import django_heroku
except Exception:
    django_heroku = None
from pathlib import Path
from datetime import timedelta
import cloudinary
#import crispy_forms

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='unsafe-dev-key')
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','tools-and-jobs.herokuapp.com','127.0.0.1:8000','www.toolsandjobs.info','toolsandjobs.info']


# Application definition

INSTALLED_APPS = [

    'django.contrib.sites',
    'django.contrib.sitemaps',
    'jobs.apps.JobsConfig',
    'techmcq.apps.TechmcqConfig',
    'engifree.apps.EngifreeConfig',
    'signup.apps.SignupConfig',
    'webtools1.apps.Webtools1Config',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # optional third-party apps (added below if available)
    "rest_framework", # for jwt auth
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'URLshortner',
    'login',
    'register',
    'accounts',
    'axes', # for brute-force attack protection
]

AUTH_USER_MODEL = 'accounts.User'

# Try to import optional third-party apps and append them only if available.
optional_third_party = [
    ('cloudinary_storage', 'cloudinary_storage'),
    ('cloudinary', 'cloudinary'),
    ('ckeditor', 'ckeditor'),
    ('ckeditor_uploader', 'ckeditor_uploader'),
    ('crispy_bootstrap4', 'crispy_bootstrap4'),
    ('crispy_forms', 'crispy_forms'),
]

for module_name, app_label in optional_third_party:
    try:
        __import__(module_name)
        INSTALLED_APPS.append(app_label)
    except Exception:
        # missing optional dependency; continue without adding the app
        pass

# jwt auth settings

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # keep other auth classes if you need session auth for admin etc.
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    # recommended: short-lived access token + longer refresh token
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),         # Access short (refresh to keep logged in)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),            # <-- user stays logged in 7 days
    'ROTATE_REFRESH_TOKENS': True,                          # rotate refresh tokens (more secure)
    'BLACKLIST_AFTER_ROTATION': True,                       # if you add blacklist app
}


SITE_ID = 1
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# krish add this 
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"



MIDDLEWARE = [
# SecurityMiddleware must be listed before other middleware
    'axes.middleware.AxesMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # removed duplicate SecurityMiddleware (was listed twice)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # JWT Authentication Middleware
    'MywebTools.middleware.JWTAuthMiddleware',
    

]


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 31536000
CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_HTTPONLY = False  # CSRF cookie must be readable by JS sometimes, so usually False

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
]


ROOT_URLCONF = 'MywebTools.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS = (
                   'django.core.context_processors.request',

)

WSGI_APPLICATION = 'MywebTools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_ROOT = os.path.join(BASE_DIR,'staticfiles')

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

#add config
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'hg6hswtwo',
    'API_KEY': '396924694795958',
    'API_SECRET': '0xN1lqF5mgOtcEPNUDPCWM2Mi4A',
}
#ckeditor
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'posts/'
CKEDITOR_BROWSE_SHOW_DIRS = False
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'allowedContent':True,
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'toolsandjobs@gmail.com'
EMAIL_HOST_PASSWORD = 'Shashanka@123'



django_heroku.settings(locals())
# Activate Django-Heroku if package is available.
if django_heroku:
    django_heroku.settings(locals())
