# Generated by Django 3.1.1 on 2020-09-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password2',
        ),
    ]
