# Generated by Django 3.1.1 on 2020-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200923_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('email1', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
