# Generated by Django 3.1.1 on 2020-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='job_field',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
