# Generated by Django 3.1.3 on 2020-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_signup_job_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
