# Generated by Django 5.2.7 on 2025-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_company_verified',
            field=models.BooleanField(default=False),
        ),
    ]
