# Generated by Django 3.1.3 on 2022-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Add the original URL that you want to shorten.')),
                ('key', models.CharField(help_text='Add your words to shorten URL with.', max_length=30, unique=True)),
            ],
        ),
    ]
