# Generated by Django 5.2.7 on 2025-11-08 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engifree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', models.CharField(max_length=3000)),
                ('tex', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learnfree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img5', models.ImageField(upload_to='pics')),
                ('text5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title5', models.CharField(max_length=300)),
                ('tex5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link5', models.URLField()),
                ('date_time5', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
