# Generated by Django 3.1.1 on 2020-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engifree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('tex', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
