# Generated by Django 3.1.1 on 2020-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engifree',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
