# Generated by Django 3.1.1 on 2020-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0002_auto_20200925_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devfree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pics')),
                ('text1', models.TextField()),
                ('title1', models.CharField(max_length=30)),
                ('tex1', models.TextField()),
                ('link1', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Editfree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img3', models.ImageField(upload_to='pics')),
                ('text3', models.TextField()),
                ('title3', models.CharField(max_length=30)),
                ('tex3', models.TextField()),
                ('link3', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Edufree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(upload_to='pics')),
                ('text2', models.TextField()),
                ('title2', models.CharField(max_length=30)),
                ('tex2', models.TextField()),
                ('link2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Filefree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img4', models.ImageField(upload_to='pics')),
                ('text4', models.TextField()),
                ('title4', models.CharField(max_length=30)),
                ('tex4', models.TextField()),
                ('link4', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Learnfree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img5', models.ImageField(upload_to='pics')),
                ('text5', models.TextField()),
                ('title5', models.CharField(max_length=30)),
                ('tex5', models.TextField()),
                ('link5', models.URLField()),
            ],
        ),
    ]
