# Generated by Django 3.1.1 on 2020-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0003_devfree_editfree_edufree_filefree_learnfree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devfree',
            name='title1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='editfree',
            name='title3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='edufree',
            name='title2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='engifree',
            name='title',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='filefree',
            name='title4',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='learnfree',
            name='title5',
            field=models.CharField(max_length=300),
        ),
    ]
