# Generated by Django 3.1.1 on 2020-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0004_auto_20201028_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytesttitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetitle', models.CharField(max_length=300)),
            ],
        ),
    ]
