# Generated by Django 3.1.1 on 2020-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0005_mytesttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytesttitle',
            name='teurl',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytesttitle',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
