# Generated by Django 3.1.1 on 2020-10-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0006_auto_20201030_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytesttitle',
            name='text',
        ),
    ]
