# Generated by Django 3.1.1 on 2020-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0008_auto_20201111_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devfree',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='devfree',
            name='date_time1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
