# Generated by Django 3.1.1 on 2020-11-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0009_auto_20201112_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devfree',
            options={},
        ),
    ]
