# Generated by Django 3.1.1 on 2020-11-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0010_auto_20201112_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='editfree',
            name='date_time3',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='edufree',
            name='date_time2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='engifree',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filefree',
            name='date_time4',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learnfree',
            name='date_time5',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mytesttitle',
            name='date_time1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
