# Generated by Django 3.1.3 on 2020-12-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0011_auto_20201112_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devfree',
        ),
        migrations.DeleteModel(
            name='Editfree',
        ),
        migrations.DeleteModel(
            name='Filefree',
        ),
    ]
