# Generated by Django 3.1.3 on 2021-01-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engifree', '0012_auto_20201215_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edufree',
        ),
        migrations.DeleteModel(
            name='Mytesttitle',
        ),
    ]
