# Generated by Django 5.2.7 on 2025-11-08 07:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=300, unique=True)),
                ('slug1', models.SlugField(max_length=300, unique=True)),
                ('desc', models.CharField(max_length=170, null=True)),
                ('photos1', models.ImageField(blank=True, default='pics/autocad-engifree.jpg', upload_to='pics')),
                ('contents1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('updated_on1', models.DateTimeField(auto_now=True)),
                ('created_on1', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('age_range', models.CharField(blank=True, max_length=15, null=True)),
                ('asseses', models.CharField(blank=True, max_length=200, null=True)),
                ('target_name1', models.CharField(blank=True, max_length=35, null=True)),
                ('target_name2', models.CharField(blank=True, max_length=35, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('about_name', models.CharField(blank=True, max_length=150, null=True)),
                ('que_name1', models.CharField(blank=True, max_length=150, null=True)),
                ('que_text1', models.CharField(blank=True, max_length=320, null=True)),
                ('que_hint1', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text0', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint0', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text1', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint1', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text2', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint2', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_text1', models.CharField(blank=True, max_length=150, null=True)),
                ('accepted_hint1', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_exp', models.CharField(blank=True, max_length=200, null=True)),
                ('que_name2', models.CharField(blank=True, max_length=150, null=True)),
                ('que_text2', models.CharField(blank=True, max_length=320, null=True)),
                ('que_hint2', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text00', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint00', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text11', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint11', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_text22', models.CharField(blank=True, max_length=150, null=True)),
                ('ans_hint22', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_text11', models.CharField(blank=True, max_length=150, null=True)),
                ('accepted_hint11', models.CharField(blank=True, max_length=100, null=True)),
                ('ans_expl', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='techmcq.category')),
            ],
            options={
                'ordering': ['-created_on1'],
            },
        ),
    ]
