# Generated by Django 3.1.3 on 2020-11-27 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=300, unique=True)),
                ('slug1', models.SlugField(max_length=300, unique=True)),
                ('photos1', models.ImageField(blank=True, upload_to='pics')),
                ('contents1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on1', models.DateTimeField(auto_now=True)),
                ('created_on1', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-created_on1'],
            },
        ),
    ]
