# Generated by Django 3.1.3 on 2020-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmcq',
            name='photos1',
            field=models.ImageField(blank=True, default='pics/autocad-engifree.jpg', upload_to='pics'),
        ),
    ]
