# Generated by Django 3.1.3 on 2020-11-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
