# Generated by Django 3.1.3 on 2020-12-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmcq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='techmcq.category'),
        ),
    ]
