# Generated by Django 3.1.3 on 2020-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0006_techmcq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmcq',
            name='desc',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
