# Generated by Django 3.1.3 on 2020-12-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0007_techmcq_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmcq',
            name='desc',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
