# Generated by Django 3.1.3 on 2021-04-18 06:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0008_auto_20201218_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmcq',
            name='script_data',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
