# Generated by Django 3.1.3 on 2021-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0009_techmcq_script_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmcq',
            name='script_data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
