# Generated by Django 3.1.3 on 2021-04-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0010_auto_20210418_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techmcq',
            name='script_data',
        ),
    ]
