# Generated by Django 3.1.3 on 2021-04-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0012_auto_20210418_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmcq',
            name='ans_exp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
