# Generated by Django 3.1.3 on 2021-05-07 11:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmcq', '0013_techmcq_ans_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmcq',
            name='contents1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
