# Generated by Django 5.2.7 on 2025-11-08 07:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busi_Management_administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head6', models.CharField(max_length=300)),
                ('desc6', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url6', models.URLField()),
                ('photo6', models.ImageField(upload_to='pics')),
                ('date_time6', models.DateTimeField(auto_now=True)),
                ('exper6', models.CharField(max_length=30)),
                ('vacc6', models.CharField(max_length=100)),
                ('loc6', models.CharField(max_length=100)),
                ('sal6', models.CharField(max_length=30)),
                ('skil6', models.CharField(max_length=1000)),
                ('descr6', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ind_type6', models.CharField(max_length=100)),
                ('func_area6', models.CharField(max_length=100)),
                ('role6', models.CharField(max_length=100)),
                ('empl_type6', models.CharField(max_length=70)),
                ('edu_or_elig6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head9', models.CharField(max_length=300)),
                ('desc9', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url9', models.URLField()),
                ('photo9', models.ImageField(upload_to='pics')),
                ('date_time1', models.DateTimeField(auto_now=True)),
                ('exper9', models.CharField(max_length=30)),
                ('vacc9', models.CharField(max_length=100)),
                ('loc9', models.CharField(max_length=100)),
                ('sal9', models.CharField(max_length=30)),
                ('skil9', models.CharField(max_length=1000)),
                ('descr9', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ind_type9', models.CharField(max_length=100)),
                ('func_area9', models.CharField(max_length=100)),
                ('role9', models.CharField(max_length=100)),
                ('empl_type9', models.CharField(max_length=70)),
                ('edu_or_elig9', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=300)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('photo', models.ImageField(upload_to='pics')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('exper', models.CharField(max_length=30)),
                ('vacc', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('sal', models.CharField(max_length=30)),
                ('skil', models.CharField(max_length=1000)),
                ('descr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ind_type', models.CharField(max_length=100)),
                ('func_area', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('empl_type', models.CharField(max_length=70)),
                ('edu_or_elig', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head8', models.CharField(max_length=300)),
                ('desc8', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url8', models.URLField()),
                ('photo8', models.ImageField(upload_to='pics')),
                ('date_time8', models.DateTimeField(auto_now=True)),
                ('exper8', models.CharField(max_length=30)),
                ('vacc8', models.CharField(max_length=100)),
                ('loc8', models.CharField(max_length=100)),
                ('sal8', models.CharField(max_length=30)),
                ('skil8', models.CharField(max_length=1000)),
                ('descr8', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ind_type8', models.CharField(max_length=100)),
                ('func_area8', models.CharField(max_length=100)),
                ('role8', models.CharField(max_length=100)),
                ('empl_type8', models.CharField(max_length=70)),
                ('edu_or_elig8', models.CharField(max_length=100)),
            ],
        ),
    ]
