# Generated by Django 3.1.1 on 2020-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='head2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='busi_management_administration',
            name='head6',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='communication',
            name='head9',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='education',
            name='head4',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='head',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='govt_jobs',
            name='head3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='insta_repair_maintain',
            name='head7',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='law_publicpolicy',
            name='head5',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medical',
            name='head1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sales',
            name='head8',
            field=models.CharField(max_length=300),
        ),
    ]
