# Generated by Django 5.2.7 on 2025-11-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineering',
            new_name='add_jobs',
        ),
        migrations.DeleteModel(
            name='Busi_Management_administration',
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AlterModelTable(
            name='add_jobs',
            table='add_jobs',
        ),
    ]
