# Generated by Django 5.2.7 on 2025-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_engineering_add_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='add_jobs',
            name='disctrict',
            field=models.CharField(default='', max_length=100),
        ),
    ]
