# Generated by Django 3.1.1 on 2020-11-11 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201028_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
