# Generated by Django 5.2.7 on 2025-11-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_jobs_company_name_add_jobs_disctrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_jobs',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='exper',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='head',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='descr',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='loc',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='sal',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='skil',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='vacc',
            new_name='vacancy',
        ),
    ]
