# Generated by Django 3.1.1 on 2020-11-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201111_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='date_time2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='busi_management_administration',
            name='date_time6',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='date_time1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='date_time4',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='engineering',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='govt_jobs',
            name='date_time3',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insta_repair_maintain',
            name='date_time7',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='law_publicpolicy',
            name='date_time5',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='date_time1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='date_time8',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
