# Generated by Django 5.2.7 on 2025-11-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_desc_add_jobs_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_jobs',
            old_name='header',
            new_name='head',
        ),
    ]
