# Generated by Django 3.1.3 on 2021-01-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201112_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arts',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Govt_Jobs',
        ),
        migrations.DeleteModel(
            name='Insta_Repair_Maintain',
        ),
        migrations.DeleteModel(
            name='Law_publicPolicy',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
    ]
