# Generated by Django 5.2.7 on 2025-11-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_header_add_jobs_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_jobs',
            old_name='description',
            new_name='company_description',
        ),
    ]
