# Generated by Django 5.2.7 on 2025-11-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_description_add_jobs_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_jobs',
            old_name='company_description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='add_jobs',
            old_name='job_description',
            new_name='descr',
        ),
    ]
