# Generated by Django 5.2.7 on 2025-12-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_company_description_add_jobs_desc_and_more'),
        ('register', '0004_alter_company_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.company'),
        ),
    ]
